### PR TITLE
Rounded the pointy ends of NewArmShape.svg

### PR DESCRIPTION
**Pull request by mrfugu**
Added a 3mm fillet to the pointy ends of the NewArmShape. (Via Fusion360, exported to Ai as .dxf, then exported to .svg)

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Should I still merge this? Wasn't this change already added in the other pull request?

**Comment by mrfugu** [comment]
this is a resolution of Issue #32 , and is the same change I applied to the 'All_Parts_Laid_Out.svg' and the Fusion360 Project.

**Comment by BarbourSmith** [comment]
Got it. Thanks for clarifying, and thank you for helping!

**Comment by mrfugu** [comment]
no sweat, happy to help, and I can't wait to get one in my hands!

**Pull request merged**
