### PR TITLE
Replacing invalid files

### PR DESCRIPTION
**Pull request by mrfugu**
I'm not sure why these appear as 'invalid' in the current version. The File size is significantly different from my local copies, so I'm reposting them via this pull req.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
That is strange! Good catch.

This pull request is showing 'conflicts' with the master version. Usually this means that two people have edited the files in question at the same time, but I don't think anyone else has touched these files recently so it might be an issue with when this version was made vs when the previous version was made. 

I would try clicking the "sync" button in the upper right of GitHub desktop and the "Update from master" button in the upper left if it is showing up

**Comment by mrfugu** [comment]
I think I fixed everything. Still not sure what happened but each file looks like it was appended to the previous version, instead of replacing the previous version.

**Comment by BarbourSmith** [comment]
Looks perfect

**Comment by mrfugu** [comment]
thanks! and continued apologies for having to shepherd along my github learning curve. 

good luck with the shipments upcoming!

**Pull request merged**
