### PR TITLE
Add picture of tuning calibration

### PR DESCRIPTION
**Pull request by BarbourSmith**

### CODE REVIEW

**Comment by jbarchuk** [comment]
Awesome troubleshooting detail. That's the kind of 'empirical calibration'
that's needed. It saves a lot of trial/error for the user.

But the text is a ambiguous/unclear. The phrase 'distance... too large'
implies that the physical distance is too big and the user has to make the
sled smaller. I'm not sure what the phrase should be. Maybe 'Sled dimension
as recorded in the ini file is to large.'

I get the feeling that error correction could be calculable. The user
measures the square vertically and horizontally. That ratio plus an
equation tells the user how much to adjust one/them. That could be built
into the GC setup screen.

The text in the pic could describe where in the setup to make the
adjustment.

**Comment by BarbourSmith** [comment]
Great suggestions.

I'll update the text right now, and make an issue to work it into GC to be automatic. You are right that I bet we can work out at least a good guess.

**Comment by davidelang** [comment]
There are four numbers that really matter

1. distance between motors

2. distance between sled mounting points

3. drop to center of bit

4. drop to cg of sled

While I agree that if people are using a 'standard' sled, #1 is far more likely 
to be the one that's wrong, I'll point out that if people try to cut a sled 
before things get fixed, the sled they create may very well differ from the 
'standard' one.

It may be that the temp sled template process is good enough to avoid this 
problem (and even so, it's probably worth having people measure something on 
that printout in case the process of printing it shrunk it to fit added 
margines).

It would be useful for someone who has a working setup with correct measurements 
to adjust each of these four values and see what the resulting error is on the 
test shape.

I'll also point out that the error is probably going to be different in 
different areas of the work area. Towards the center, the sled is not going to 
tilt much, so #3 and #4 really aren't going to matter. But near the edge where 
the sled tilts more, those factors are going to matter more.

I would also guess that they will matter more low on the work area than high 
(because chain tension is less as you are lower on the work area)

David Lang

**Comment by BarbourSmith** [comment]
Great insight @davidelang. I think we need to keep refining our calibration technique. 

Writing a simulation of the whole system in python could go a long way towards helping us understand exactly what is happening and by how much it matters.

The next step I want to take is to automate the measuring of the machine so that we can reduce human error there.

**Pull request merged**
