### PR TITLE
edit NewArmShape + allow 1/4" bit

### PR DESCRIPTION
**Pull request by mrfugu**
I rounded the pointy ends of the NewArmShape, and slightly widened (from 6 to 7mm) the Brick Holder mounting holes, in order to allow a 1/4" (6.4mm) bit to attempt to drill them. Fusion360 wasn't happy with the size of the holes so I scaled them up just a smidge.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Looks great! Ultimately we should make these changes in the CAD model, but no rush there.

I think I would ultimately like to move away from Sketchup as our CAD platform

**Comment by mrfugu** [comment]
While I'm new to CAD in general, I found Fusion360 to be completely reasonable to learn (in just a week or so) with some youtube/google study and any previous experience with Adobe type programs. 

Ya'll really should take advantage of Autodesk if they're offering any local assistance (as I saw mentioned for a post processor) and it would be reasonable to consider making it the 'preferred CAD/CAM app'. 

Fusion360 is as good as you'll find for any reasonable amount of money. "Free to hobbyists, until you make $100k" kinda sounds like a challenge =) and for the kind of milling MaslowCNC is capable of, dead simple to get up and running, if not a little too feature rich. 

If there's a balk at their commercial price (~$3k/yr), I'd say to think about creating a separate 'design entity' from MaslowCNC (a 'machine sales entity') and have it use Fusion360 until it can afford the commercial license. 

Regardless, I'm happy to help whip the MaslowCNC Parts Project file into shape in Fusion360 and hope we can set ppl on their way with a file that's comprehensive enough to learn Fusion360's 'best practices' in making new project files.

**Comment by davidelang** [comment]
Maslow made more than $100K, so it is not free for them to use.

it's $100K in recipts, not in profit.

Personally, I steer away from autodesk due to their behavior (lawsuits, etc)

onshape is similar and has no income limits, but it has export limits.

**Comment by mrfugu** [comment]
Like I said, perhaps MaslowCNC (and whatever legal entity manages it) doesn't use Fusion360, perhaps a new and different concern does, and its function is creating things with a MaslowCNC. either way, its a good tool for things MaslowCNC can make, both for design and milling, and having them in your own backyard as it were is an added bonus. I'll continue to try to make the MaslsowCNC Parts file as comprehensive as I can, ya'll are welcome to assist, otherwise I'll just have it follow along with whatever changes are made along the way.

**Comment by davidelang** [comment]
well, it's hard to make that argument and have Bar publicly using Fusion360 as 
the tool for working on the design of the maslow machine.

**Comment by mrfugu** [comment]
technically, i think the Fusion360 file I linked is 'my' copy of an open sourced design, but I'm no lawyer, so whatever. I'm not gonna split hairs, I think it's a pretty neat application, and Autodesk seems, on the surface at least, to make many accommodations for many different machines and use cases. 

And again, they seemed (based on my reading of the forums) to be at least a little keen on MaslowCNC, and are in fact, quite nearby to Barbour and Hannah relatively. Those things are assets in my opinion.

**Pull request merged**
