### PR TITLE
Filling in part numbers and sources

### PR DESCRIPTION
**Pull request by JDogHerman**
Making some serious guesses. Obviously McMaster is going to be expensive but they have lots of info on the items they carry.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
I feel weird about putting these part numbers in the official BOM because it's really not what comes in the box. A lot of people use the BOM to check that they recieved all the parts when they open the box, and these won't be what they see.

How would you feel about a second BOM on a wiki page which lists alternative sources for the parts with a reference link to the page in the BOM here? I want to make it clear to people that these aren't the part's I've used, or which come in the kit, but I also think having a buy list that's tested by the community to scratch build a machine is a great thing

**Comment by JDogHerman** [comment]
I am not sure what the Product has in store (as I missed the kickstart and first round of sales) but I am looking to build a DIY rig and thought these changes could help someone else.

@BarbourSmith It make sense to separate the two paths. The MaslowCNC product vs The MaslowCNC project. Would it be better to create a permanent forked repo focused on a DIY MaslowCNC or transition the product details to a wiki?

Personally I like the idea of having a MaslowCNC project repo as it lends itself to community contribution as the design evolves.

**Comment by davidelang** [comment]
I think it's ok to make a new column in the spreadsheet for 'equivalent parts 
from other sources' or similar

**Comment by mrfugu** [comment]
Added DIY Kit Equivalent Parts](https://github.com/MaslowCNC/Mechanics/wiki/DIY-Kit-Equivalent-Parts) list page to the wiki
This issue can be closed.

**Pull request closed without merging**
